### ISSUE TITLE
FlatList not scrolling

### ISSUE THREAD

**Issue by unicscode** [LonelyCpp/react-native-metro-tabs#4]
Hello;
the flatlist on top free screen is not scrolling correctly . in the demo ther is just three item, so you can't see it but if you add more items to sampleStoreData array, the flatlist are not scrolling correctly

![ezgif com-crop](https://user-images.githubusercontent.com/5501077/63060413-76712380-bef2-11e9-86f9-3964fc707041.gif)

**Comment by LonelyCpp** [comment]
Sorry, I was super new to github and missed this. Here I am a year later thinking wtf I have issues on this repo!! 😭 

The code is now much better, please give it another shot
