### ISSUE TITLE
parallax effect

### ISSUE THREAD

**Issue by obiwankenoobi** [LonelyCpp/react-native-metro-tabs#5]
Hey, great work on it! 

I wonder how did you created the parallax effect of the header labels against the screens? Couldn't find it in the source code. Would love to read through, 

Thanks!(:

**Comment by LonelyCpp** [comment]
sorry dude, I'm a year late. If you're still curious [here](https://github.com/LonelyCpp/react-native-metro-tabs/blob/1029471c3b4d6955d58ba632ba328050801c9455/src/MetroTabs.js#L31) is the interpolation
